apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-postgres
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: flaskdb
            - name: POSTGRES_USER
              value: flaskuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-postgres
                  key: postgresql-password
          ports:
            - containerPort: 5432
