apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-registration-ingress
  namespace: application
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: flask.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-registration-user-registration-chart
                port:
                  number: 5000
