apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-registration-chart.fullname" . }}
  namespace: application
spec:
  selector:
    app: user-registration
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
