apiVersion: v1
kind: Service
metadata:
  name: user-registration
  labels:
    app: user-registration
spec:
  type: NodePort
  selector:
    app: user-registration
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
